E-Kool/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCore.Models;
using E_Kool.Data;
using E_Kool.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace E_Kool.Controllers
{

    [Authorize]
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public StudentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            List<Student> students;

            // Lauri kood

            if (User.IsInRole("Student"))
            {
                string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                
                var currentUserWithClass = _context.Student.Include(x => x.SchoolClass).Where(x => x.ApplicationUserId == userId).FirstOrDefault();

                students = await _context.Student
                 .Include(x => x.SchoolClass)
                 .Where(x => x.SchoolClass.Id == currentUserWithClass.SchoolClass.Id)
                 .ToListAsync();


            }
            else if (User.IsInRole("Headteacher") || User.IsInRole("Principle"))
            {
                students = await _context.Student
                 .Include(x => x.SchoolClass)
                 .OrderBy(x => x.SchoolClass)

                 .ToListAsync();
                foreach (var student in students)
                {
                    var studentGrades = _context.StudentSubjectGrades
                         .Include(x => x.Grade)
                         .Where(x => x.StudentId == student.Id && x.Grade.GradeValue != 0).ToList();
                    if(studentGrades.Count > 0)
                    {
                        student.AverageGrade = Math.Round(studentGrades.Average(x => x.Grade.GradeValue), 2);

                    }

                }
            }
            else
            {
                 students = await _context.Student
                     .Include(x => x.SchoolClass)
                     .ToListAsync();
            }



            return View(students);
        }


        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }
            ViewData["SchoolClassId"] = new SelectList(_context.SchoolClass, "Id", "ClassCode");
            ViewData["SubjectsId"] = new SelectList(_context.Subject, "Id", "SubjectName");
            return View(student);
        }



        // GET: Students/Create


        public IActionResult Create()
        {
            if (User.IsInRole("Admin")) //See koodijupp pange juurde, kui tahate kellelegi mingi tegevuse jaoks õiguse anda
            {
                ViewData["SchoolClassId"] = new SelectList(_context.SchoolClass, "Id", "ClassCode");
                ViewData["SubjectsId"] = new SelectList(_context.Subject, "Id", "SubjectName");
                return View();

            }
            else
            {
                return Content("Ainult admin saab õpilasi lisada");
            }


        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,Email,LastName,IdCode,SchoolClassId,SubjectsId,GradeOne")] Student student)
        {
            if (ModelState.IsValid)
            {

                var user = new ApplicationUser()
                {

                    UserName = student.Email,// sama mis email
                    Email = student.Email,
                };
                await _userManager.CreateAsync(user, "A123!a");// määratud parool igale õpilasele
                await _userManager.AddToRoleAsync(user, "Student"); // kasutajale läheb adminni roll

                student.ApplicationUserId = user.Id;

                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            List<Student> students = _context.Student
                  .Include(x => x.SchoolClass)
                  .OrderBy(x => x.FirstName)
           .ToList();
            return View(students);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }

            ViewData["SchoolClassId"] = new SelectList(_context.SchoolClass, "Id", "ClassCode");
            ViewData["SubjectsId"] = new SelectList(_context.Subject, "SubjectId", "SubjectName");
            return View(student);


        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,IdCode,SchoolClassId,SubjectsId,GradeOne")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Student.FindAsync(id);
            _context.Student.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Student.Any(e => e.Id == id);
        }
    }


}

E-Kool/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCore.Models;
using E_Kool.Data;

namespace E_Kool.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SubjectsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            var subjects = await _context.Subject
          .OrderBy(x => x.Id)
          .ToListAsync();
            return View(subjects);
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subjects/Create
        public IActionResult Create()
        {
            if (User.IsInRole("Headteacher"))
            {
           
                return View();
            }
            else
            {
                return Content("Ainult õppealajuhataja saab aineid lisada");
            }
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SubjectName")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SubjectName")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _context.Subject.FindAsync(id);
            _context.Subject.Remove(subject);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectExists(int id)
        {
            return _context.Subject.Any(e => e.Id == id);
        }
    }
}

E-Kool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Kool</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @* lisab menüüikooni mida saab klikkida *@
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="https://secure1.suhtlus.ee/download/?shareid=23ce97f4-99eb-4d93-8eff-4eace762e4ac&fileid=53de0916-bd56-49fb-9e55-211cb4d3132d&x=a.jpg" alt="Site Logo" style="height:33px; width: 100px" />
                </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">E_Kool</a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @* Menüünimed eestikeelseks *@

                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Kodu</a></li>*@

                    @*<li><a asp-area="" asp-controller="Students" asp-action="Index">Õpilased</a></li>
        <li><a asp-area="" asp-controller="Teachers" asp-action="Index">Õpetajad</a></li>
        <li><a asp-area="" asp-controller="Subjects" asp-action="Index">Õppeained</a></li>
        <li><a asp-area="" asp-controller="SchoolClasses" asp-action="Index">Klassid</a></li>*@

                    @*Menüü autoriseerimine:*@
                    @*@if (User.IsInRole("<rolli nimi>")) { <menüü listi link> }*@

                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Students" asp-action="Index">Õpilased</a></li>
                        <li><a asp-area="" asp-controller="Teachers" asp-action="Index">Õpetajad</a></li>
                    }

                    @if (User.IsInRole("Principle"))
                    {
                        <li><a asp-area="" asp-controller="Students" asp-action="Index">Õpilased</a></li>
                        <li><a asp-area="" asp-controller="Teachers" asp-action="Index">Õpetajad</a></li>
                    }

                    @if (User.IsInRole("Headteacher"))
                    {
                        <li><a asp-area="" asp-controller="Students" asp-action="Index">Õpilased</a></li>
                        <li><a asp-area="" asp-controller="Teachers" asp-action="Index">Õpetajad</a></li>
                        <li><a asp-area="" asp-controller="Subjects" asp-action="Index">Õppeained</a></li>
                        <li><a asp-area="" asp-controller="SchoolClassSubjects" asp-action="Index">Klassid</a></li>
                        <li><a asp-area="" asp-controller="SchoolClasses" asp-action="Index">Kallak</a></li>
                        <li><a asp-area="" asp-controller="StudentSubjectGrades" asp-action="Index">Hindamine</a></li>
                    }

                    @if (User.IsInRole("Student"))
                    {
                        <li><a asp-area="" asp-controller="StudentSubjectGrades" asp-action="Index">Minu hinded</a></li>
                        <li><a asp-area="" asp-controller="Students" asp-action="Index">Minu klassikaaslased</a></li>
                        <li><a asp-area="" asp-controller="SchoolClassSubjectTeachers" asp-action="Index">Minu õppeained</a></li>
                    }

                    @if (User.IsInRole("Teacher"))
                    {
                        <li><a asp-area="" asp-controller="StudentSubjectGrades" asp-action="Index">Õpilaste hinded</a></li>
                    }


                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - E_Kool</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>